// Command genvectors emits the shared E2EE test vectors consumed by both
// this module's tests and the Dart mirror (olace-crypto-dart). Two
// independent implementations agreeing on these bytes is the compatibility
// proof: any drift in salts, transcripts, AAD construction, or envelope
// framing fails CI on one side or the other.
//
// All inputs are fixed constants (RFC 7748 X25519 scalars plus fixed
// nonces), so the output is fully deterministic and safe to publish.
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdh"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"

	"github.com/Olace-app/olace-e2ee-go/e2ee"
)

func mustHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}

func mustPriv(scalarHex string) *ecdh.PrivateKey {
	k, err := ecdh.X25519().NewPrivateKey(mustHex(scalarHex))
	if err != nil {
		panic(err)
	}
	return k
}

// Fixed scalars. Alice and Bob are the RFC 7748 section 6.1 test keys;
// the ephemerals are arbitrary fixed constants.
const (
	aliceScalar = "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a"
	bobScalar   = "5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb"
	ephAScalar  = "a8abababababababababababababababababababababababababababababab6b"
	ephBScalar  = "c8cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd4d"
)

// Fixed handshake field values shared with the Dart generator.
var fields = map[string]any{
	"ticket":              "ticket-0001",
	"pair_id":             "pair-0001",
	"user_id":             "user-0001",
	"mobile_device_id":    "didv1_mobile0001",
	"desktop_device_id":   "didv1_desktop0001",
	"mobile_key_version":  3,
	"desktop_key_version": 5,
	"session_id":          "sess-0001",
	"client_eph_pub_b64":  "", // filled below
	"server_eph_pub_b64":  "",
	"client_nonce":        "Y2xpZW50LW5vbmNlLTAwMDE=",
	"server_nonce":        "c2VydmVyLW5vbmNlLTAwMDE=",
}

func gcmSeal(key, nonce, plaintext, aad []byte) (ciphertext, tag []byte) {
	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		panic(err)
	}
	sealed := gcm.Seal(nil, nonce, plaintext, aad)
	return sealed[:len(sealed)-16], sealed[len(sealed)-16:]
}

func main() {
	alice := mustPriv(aliceScalar)
	bob := mustPriv(bobScalar)
	ephA := mustPriv(ephAScalar)
	ephB := mustPriv(ephBScalar)

	sharedAB, err := alice.ECDH(bob.PublicKey())
	if err != nil {
		panic(err)
	}

	out := map[string]any{
		"comment": "Shared E2EE test vectors for olace-e2ee-go and olace-crypto-dart. Generated by cmd/genvectors; deterministic, fixed inputs only.",
		"x25519": map[string]any{
			"alice_scalar_hex":     aliceScalar,
			"alice_public_hex":     hex.EncodeToString(alice.PublicKey().Bytes()),
			"bob_scalar_hex":       bobScalar,
			"bob_public_hex":       hex.EncodeToString(bob.PublicKey().Bytes()),
			"eph_a_scalar_hex":     ephAScalar,
			"eph_a_public_hex":     hex.EncodeToString(ephA.PublicKey().Bytes()),
			"eph_b_scalar_hex":     ephBScalar,
			"eph_b_public_hex":     hex.EncodeToString(ephB.PublicKey().Bytes()),
			"shared_alice_bob_hex": hex.EncodeToString(sharedAB),
		},
		"fields": fields,
	}

	clientEphPubB64 := base64.StdEncoding.EncodeToString(ephA.PublicKey().Bytes())
	serverEphPubB64 := base64.StdEncoding.EncodeToString(ephB.PublicKey().Bytes())
	fields["client_eph_pub_b64"] = clientEphPubB64
	fields["server_eph_pub_b64"] = serverEphPubB64

	f := fields
	str := func(k string) string { return f[k].(string) }
	num := func(k string) int { return f[k].(int) }

	// ── Transcripts ──
	p2pHello := e2ee.BuildP2PHelloTranscript(
		str("ticket"), str("pair_id"), str("user_id"), str("mobile_device_id"), str("desktop_device_id"),
		num("mobile_key_version"), num("desktop_key_version"),
		str("session_id"), clientEphPubB64, str("client_nonce"))
	p2pAck := e2ee.BuildP2PAckTranscript(
		str("ticket"), str("pair_id"), str("user_id"), str("mobile_device_id"), str("desktop_device_id"),
		num("mobile_key_version"), num("desktop_key_version"),
		str("session_id"), clientEphPubB64, serverEphPubB64, str("client_nonce"), str("server_nonce"))
	p2pSessionInfo := e2ee.BuildP2PSessionInfo(
		str("ticket"), str("pair_id"), str("user_id"), str("mobile_device_id"), str("desktop_device_id"),
		num("mobile_key_version"), num("desktop_key_version"),
		str("session_id"), clientEphPubB64, serverEphPubB64, str("client_nonce"), str("server_nonce"))
	relayHello := e2ee.BuildSecureRelayHelloTranscript(
		str("pair_id"), str("user_id"), str("mobile_device_id"), str("desktop_device_id"),
		num("mobile_key_version"), num("desktop_key_version"),
		str("session_id"), serverEphPubB64, str("server_nonce"))
	relayAck := e2ee.BuildSecureRelayAckTranscript(
		str("pair_id"), str("user_id"), str("mobile_device_id"), str("desktop_device_id"),
		num("mobile_key_version"), num("desktop_key_version"),
		str("session_id"), serverEphPubB64, clientEphPubB64, str("server_nonce"), str("client_nonce"))
	relayFsInfo := e2ee.BuildSecureRelayForwardSecretSessionInfo(
		str("pair_id"), str("user_id"), str("mobile_device_id"), str("desktop_device_id"),
		num("mobile_key_version"), num("desktop_key_version"),
		str("session_id"), serverEphPubB64, clientEphPubB64, str("server_nonce"), str("client_nonce"))

	// ── Keys ──
	authKey, err := e2ee.DeriveAuthKey(alice, bob.PublicKey(), str("mobile_device_id"), str("desktop_device_id"))
	if err != nil {
		panic(err)
	}
	p2pSessionKey, err := e2ee.DeriveSessionKey(alice, bob.PublicKey(), ephA, ephB.PublicKey(), p2pSessionInfo)
	if err != nil {
		panic(err)
	}
	relayFsKey, err := e2ee.DeriveForwardSecretSessionKey(ephA, ephB.PublicKey(), relayFsInfo)
	if err != nil {
		panic(err)
	}

	out["transcripts"] = map[string]any{
		"p2p_hello":        map[string]string{"transcript": p2pHello, "hmac_b64": e2ee.SignTranscript(authKey, p2pHello)},
		"p2p_ack":          map[string]string{"transcript": p2pAck, "hmac_b64": e2ee.SignTranscript(authKey, p2pAck)},
		"relay_hello":      map[string]string{"transcript": relayHello, "hmac_b64": e2ee.SignTranscript(authKey, relayHello)},
		"relay_ack":        map[string]string{"transcript": relayAck, "hmac_b64": e2ee.SignTranscript(authKey, relayAck)},
		"p2p_session_info": p2pSessionInfo,
		"relay_fs_info":    relayFsInfo,
	}
	out["derived_keys"] = map[string]string{
		"auth_key_hex":        hex.EncodeToString(authKey),
		"p2p_session_key_hex": hex.EncodeToString(p2pSessionKey),
		"relay_fs_key_hex":    hex.EncodeToString(relayFsKey),
	}

	// ── Identity fingerprint (SHA-256 hex of raw public key bytes) ──
	fp := sha256.Sum256(alice.PublicKey().Bytes())
	out["fingerprint"] = map[string]string{
		"public_key_b64":  base64.StdEncoding.EncodeToString(alice.PublicKey().Bytes()),
		"fingerprint_hex": hex.EncodeToString(fp[:]),
	}

	// ── Envelope decrypt vectors (nonces are random at encrypt time, so
	// compatibility is pinned decrypt-direction: both implementations must
	// accept these exact wire bytes). AAD is "session|seq|senderKeyVersion". ──
	envelopes := []map[string]any{}
	for _, ev := range []struct {
		name    string
		keyHex  string
		seq     int
		keyVer  int
		payload string
		nonce   string
	}{
		{"relay_fs_seq0", hex.EncodeToString(relayFsKey), 0, num("desktop_key_version"), `{"type":"token","text":"hello from the desktop","n":1}`, "000102030405060708090a0b"},
		{"p2p_seq7", hex.EncodeToString(p2pSessionKey), 7, num("mobile_key_version"), `{"type":"chat_request","prompt":"2+2?"}`, "0f0e0d0c0b0a090807060504"},
	} {
		nonce := mustHex(ev.nonce)
		aad := []byte(fmt.Sprintf("%s|%d|%d", str("session_id"), ev.seq, ev.keyVer))
		ct, tag := gcmSeal(mustHex(ev.keyHex), nonce, []byte(ev.payload), aad)
		envelopes = append(envelopes, map[string]any{
			"name":            ev.name,
			"session_key_hex": ev.keyHex,
			"envelope": map[string]any{
				"type":               "enc",
				"v":                  1,
				"session_id":         str("session_id"),
				"seq":                ev.seq,
				"sender_key_version": ev.keyVer,
				"nonce":              base64.StdEncoding.EncodeToString(nonce),
				"ciphertext":         base64.StdEncoding.EncodeToString(ct),
				"tag":                base64.StdEncoding.EncodeToString(tag),
			},
			"plaintext_json": ev.payload,
		})
	}
	out["envelopes"] = envelopes

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(out); err != nil {
		panic(err)
	}
}
